# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unitValue', models.FloatField(default=0.0)),
                ('unitName', models.CharField(max_length=200)),
                ('calories', models.IntegerField(default=0)),
                ('protein', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.FloatField(default=0.0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('instruction', models.TextField()),
                ('fromRecipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ManyToManyField(to='recipes.Step'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fromRecipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fromStep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Step'),
        ),
    ]
