# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
